@startuml
!pragma useVerticalIf on
title HMS Activity Diagram
start
:Home Page;
if (want to sign in?) then (yes)
    if (have an account ?) then (yes)
        if (forget password ?) then (yes)
            :Reset password via email;
        endif
    else (no)
        :Register;
    endif
    :Sign In;
    :Dashboard;
    if (AppointmentIn30Day) then (yes)
        if (new appointment) then (yes)
            if (do not know disease & service ?)
                :Disease & Services by Symptoms;
             endif
            :Book an Appointment;
        elseif (check appointments)
            :Get his Appointments;
        elseif (change appointments)
            :Delay/Cancel an Appointment;
        elseif (pay for appointments)
            :Make Payments;
        endif
    elseif (AppointmentByHour) then (yes)
        if (check appointments)
            :Get his Appointments;
         elseif (change appointments)
            :Delay/Cancel an Appointment;
        elseif (start appointments)
            :CheckIn an Appointment;
        endif
    elseif (Admin) then (yes)
        if (manage patients)
            :CRUD all Patients;
        elseif (manage practitioners)
            :CRUD all Practitioners;
        elseif (manage appointments)
            :CRUD all Appointments;
        endif
    endif
else (no)
    if (do not know disease & service ?) then (yes)
        :Disease & Services by Symptoms;
    endif
    stop
endif
stop
@enduml