@startuml

title Reset Password Sequence

actor user as U
boundary website as W
control api
entity authentication as A
entity mailer as M
database Postgres as P

U -> W ++: GET /reset-password?token=...
W -> api ++: /validate-token
api -> api ++: validate_token(token)
api--
alt token verified
    api -> api++: decode_token(token)
    api--
    api -> api++: compare(now,token.expire_time)
        alt token not expired
            W <-- api: token data
            U <-- W: reset password form
            U -> W++: submit reset password form
            W -> api++: POST /reset-password
            api -> A++: reset_password(id,pw)
            A -> P++: update query
            return update successful
            return success
            return success
            return reset successful announcement\nand redirect to login page
        else token expired
            W <-- api: invalid token
            api--
            W -> W++: GET /forget-password
            W--
            U <-- W: invalid token announcement\nand redirect to email form
        end
else token verifying failed
    return invalid token
    W -> W++: GET /forget-password
    W--
    return invalid token announcement\nand redirect to email form
end
@enduml