@startuml
title Check In Appointment

actor practitioner as U
actor patient as Pt
boundary website as W
control api
entity appointment as A
entity payment_gateway as G
database Postgres as P

U -> W+: GET /dashboard
W -> api+: POST /dashboard
api -> api+: user_data=req.session.user_data
api--
api -> A+: appointment_list(user_data)
A -> P+: query appointments
A <-- P: rows
P--
api <-- A: appointments list
A--
W <-- api: appointments list
api--
U <-- W: dashboard
Pt <-- W: payment notification

Pt -> G++: make payment
W <-- G--: payment success confirmation
U <-- W--: payment success confirmation

U -> W+: GET /check-in?appointment_id=...
U <-- W-: check in form
loop input is invalid
U -> W+: submit check in form
W -> W+: validate inputs
W--
U <-- W: invalid input warning
end
W -> api+: POST /save_appointment\ndata: ...
api -> A+: save_appointment(data)
A->P+: update
return
return
return
return successful appointment
@enduml