@startuml
title Reset Password Sequence

actor user as U
boundary website as W
control api
entity authentication as A
entity mailer as M
database Postgres as P

U -> W: GET /reset-password?token=...
activate W
alt token verified
    W -> api: /validate-token
    activate api
    api -> api: validate_token(token)
    api -> api: decode_token(token)
    api -> api: compare(now,token.expire_time)
        alt token not expired
             W <-- api: token data
             U <-- W: reset password form
             U -> W: submit reset password form
             W -> api: POST /reset-password
             api -> A: resetpassword(id,pw)
             A -> P: update query
             A <-- P: update successful
             api <-- A: success
             W <-- api: success
             U <-- W: reset successful announcement\nand redirect to login page
        else invalid token
             W <-- api: invalid token
             W -> W: GET /forget-password
             U <-- W: invalid token announcement\nand redirect to email form
        end
else invalid token
    activate W
    W -> api: /validate-token
    api -> api: validate_token(token)
    deactivate api
    W <-- api: invalid token
    W -> W: GET /forget-password
    U <-- W: invalid token announcement\nand redirect to email form
    deactivate W
end
@enduml